### ISSUE TITLE
Hinweis, dass kein Benutzer eingegeben werden darf

### ISSUE THREAD

**Issue by bibber0612** [1DSAG/ATC-Best-Practice-Guide#10]
Auf Seite 19 wird hingewiesen, dass eine SAP Code Inspector Variante angelegt werden soll. Hier sollte darauf hingewiesen, dass bei der SAP Code Inspector Variante kein Benutzername drin stehen darf. Ansonsten verweist das Satellitensystem auf eine nicht zu findende Variante.

**Comment by lechnerc77** [comment]
Danke für den Hinweis. Wird in der nächsten Ausgabe ergänzt

**Comment by lechnerc77** [comment]
@bibber0612 ich bin gerade die Issues in den ATC Leitfaden einzubauen. Bei diesem Issue ist mir nicht klar, an welcher Stelle die Anmerkung bzgl. des Benutzers hinzugefügt werden soll. Textstelle ist: 
_Erstellen Sie im Code Inspector (Transaktion SCI oder aus ATC heraus) auf dem zentralen Prüfsystem eine Prüfvariante, die ausschließlich RFC-fähige Prüfungen beinhaltet. Ansonsten kann die Variante nicht in den Satellitensystemen als Remote-Prüfvariante ausgewählt werden. Prüfungen mit einer markierten Checkbox „RFC-based“ erfüllen dieses Kriterium._

Hier  gibt es keine dedizierte Userein-/angabe. Please advice

**Comment by lechnerc77** [comment]
Die aktualisierte Version ist auf der DSAG Seite verfügbar [https://www.dsag.de/leitfaden_atc](https://www.dsag.de/leitfaden_atc).
Ich habe ergänzt, dass es sich um eine globale Variante handeln muss. Die Thematik mit der Eingabe eines Verantwortlichen habe ich nicht ergänzt, da dies, ein Bug ist (Abstimmung mit Thomas Fiedler findet ja berets statt
