### ISSUE TITLE
Hinweis auf Transaktion

### ISSUE THREAD

**Issue by bibber0612** [1DSAG/ATC-Best-Practice-Guide#11]
Auf Seite 16 sollte die Transaktion für das ABAP Test Cockpit genannt werden - Transaktion ATC .

**Comment by lechnerc77** [comment]
Danke für den Hinweis. Wird in der nächsten Ausgabe ergänzt

**Comment by lechnerc77** [comment]
Die aktualisierte Version ist auf der DSAG Seite verfügbar [https://www.dsag.de/leitfaden_atc](https://www.dsag.de/leitfaden_atc)
